version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '10.14.2'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
      - run: yarn test